name: my_school_erp
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=2.7.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.0
    stacked: ^1.7.1+1
    # stacked_services: ^0.4.4+3
    stacked_services: ^0.6.0+1
    responsive_builder: ^0.1.4
    logger: ^0.7.0+2
    get_it: ^3.0.3
    auto_route: ^0.6.1
    injectable: ^0.4.0+1
dev_dependencies:
    flutter_test:
        sdk: flutter
    injectable_generator: null
    auto_route_generator: null
    build_runner: null
    
flutter:
    uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
      
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
      
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
      
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages