# Use docker build the container image
## docker build -t flutter-web-builder .
# If you have some problem during cache, you can clean cache by this
## docker build --no-cache -t flutter-web-builder .
# Run the docker image with localhost 80 port.
## docker run -d -p 80:80 flutter-web-builder

FROM ubuntu:20.04

# Prerequisites
RUN apt-get update 
RUN apt-get install -y unzip xz-utils git openssh-client curl python3
RUN apt-get clean
# RUN rm -rf /var/cache/apt

# Install flutter beta
# check this site https://flutter.dev/docs/development/tools/sdk/releases?tab=linux
RUN curl -L https://storage.googleapis.com/flutter_infra/releases/beta/linux/flutter_linux_1.24.0-10.2.pre-beta.tar.xz | tar -C /opt -xJ
# RUN curl -L http://192.168.1.240/flutter_linux_1.24.0-10.2.pre-beta.tar.xz | tar -C /opt -xJ
# run http-server . -p 80 in windows after downloading flutter_linux_1.24.0-10.2.pre-beta.tar.xz
# the trick above will help you to create image faster, due to slow internet in DZ
ENV PATH "$PATH:/opt/flutter/bin"

# Run flutter doctor
RUN flutter doctor
# Enable flutter web
RUN flutter config --enable-web

#download web SDK
WORKDIR /tmp
RUN flutter create myapp
WORKDIR /tmp/myapp
RUN flutter build web
WORKDIR /tmp
RUN rm -R myapp


