
FROM node:14.15-alpine as debug

WORKDIR /work/

# Expose the port 3000
EXPOSE 3000

COPY ./package.json /work/package.json
RUN npm install
RUN npm install -g nodemon

# COPY . .
COPY . /work/src/

ENTRYPOINT [ "nodemon","--inspect=0.0.0.0", "./server.js" ]

# FROM node:14.1-alpine as prod

# WORKDIR /work/
# COPY ./src/package.json /work/package.json
# RUN npm install
# COPY ./src/ /work/

# CMD node .