
FROM node:14.15-alpine 

# Create app directory
WORKDIR /usr/src/app

# Install dependencies
COPY package.json .
RUN npm install

# Bundle app source
COPY ./src .
COPY ./public .
COPY ./school-erp-ef01f-firebase-adminsdk-8nouk-98c56d46f6.json .
COPY ./config.env .

ENV NODE_ENV=production

ENTRYPOINT [ "npm", "start" ]
