# This is a basic workflow to help you get started with Actions

name: Build, Release app to Github Pages and Firebase Hosting
# name: Test, Build and Release apk
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - online

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_job:
    container:
      image: flutter-web-builder
      volumes:
        - frontend/my_school_web:/frontend/my_school_web
      options: --cpus 8
